---
name: Markdown Link Checker

on: [push, pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Markdown link checker
        uses: gaurav-nelson/github-action-markdown-link-check@v1
