---
name: Secret Scanner

on: [push, pull_request]

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run TruffleHog Secret Scanner
        uses: trufflesecurity/trufflehog@main
