---
name: Validate Workflow JSON

on: [push, pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate all JSON files with jq
        run: |
          echo "Validating JSON files..."
          find . -name "*.json" | while read file; do
            echo "Checking $file"
            jq empty "$file" || exit 1
          done
